---
- name: "Lab exercise 4 - 8"
  hosts: webservices
  tasks:
  - name: Command to create a temp directory to host the repo
    file: path=/tmp/test state=directory
  - name: Command to clone git repo
    git: repo=https://github.com/scmgalaxy/ansible-role-template clone=yes dest=/tmp/test
...
