---
- name: "Lab exercise 4 - 9 Merging of all previous commands"
  hosts: webservices
  tasks:
  - name: Create a group called deploy
    group: name=deploy state=present
  - name: Create a user called deploy-user which is part of group called deploy
    user: name=deploy-user group=deploy
  - name: Command to install package named httpd
    yum:  name=httpd state=present
  - name: Commands to start and enable the service named “httpd”
    service: name=httpd state=started
  - name: Commands to create a file called “index.html” in /var/www/html with some dummy html contents.
    file: path=/var/www/html state=directory
  - name: Commands to create a file called “index.html” in /var/www/html with some dummy html contents.
    file: dest=/var/www/html/index.html mode=600 state=touch
  - name: Commands to create a file called “index.html” in /var/www/html with some dummy html contents.
    lineinfile: dest=/var/www/html/index.html line='<html> <h1> Welcome to HP Ansible classes </h1>  </html> '
  - name: Commands to install a package called “git”, “wget”.
    yum: name=git,wget state=present
  - name: Command to create a temp directory to host the repo
    file: path=/tmp/test state=directory
  - name: Command to clone git repo
    git: repo=https://github.com/scmgalaxy/ansible-role-template clone=yes dest=/tmp/test
  - name: Command to reboot a machine.
    reboot:

...
